spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: NEVER

logging:
  level:
    org.springframework.boot.context.config: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET}